POST http://localhost:3000/toner-changes/create
Content-Type: application/json

{
  "toner": {
    "id": "65d796ceb49ac852a330601c",
    "name": "Brother",
    "color": "black"
  },
  "printer": {
    "id": "65a03518cc187e24b408ed6a",
    "name": "Impresora Brother en kiosko de supervisor de Celda 6"
  },
  "coments": "Se cambió el toner por agotamiento",
  "created_at": "2024-02-29T15:35:16.000Z",
  "updated_at": "2024-02-29T15:35:16.000Z"
}
